version: '3'
services:
  letscode:
    build: .
    ports:
      - "6000:6000"
    links:
      - database
    env_file:
      - ./credentials.env
    depends_on:
      - database
  database:
    restart: always
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./credentials.env
volumes:
  pgdata:
